#!/bin/sh


echo Committing docker image changes for RabbitMQ transport and Photon Event Store...
sudo docker commit photon muon/photon 
sudo docker commit rabbit-muon muon/rabbit-muon 

echo Stopping RabbitMQ transport and Photon Event Store...
docker stop photon
docker stop rabbit-muon


echo Starting RabbitMQ transport and Photon Event Store...
docker start rabbit-muon
docker start photon
