---
# This playbook deploys the whole ASAP site to a test environment

#Builds base box with NodeJS, Java, Clojure, Muon & Photon
- name: apply common configuration to all nodes
  hosts: all
  sudo: true
  remote_user: vagrant

  roles:
    - common

#Configures environment based on variables, startes Photon, RabbitMQ et al.
- name: apply ASAP test configuration to all nodes
  hosts: all
  sudo: true
  remote_user: vagrant

  roles:
    - test
